### ISSUE TITLE
How do we want to allow extending "parts of the page"?

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/sphinx-basic-ng#2]
Right now, I've taken the approach of having a Jinja2 block that "wraps" an include of a template file named `elements/{whatever}.html`. The wrapper tags have classes that are directly used in the `skeleton.css` file.

This is what it looks like right now:

https://github.com/pradyunsg/sphinx-basic-ng/blob/678a10d27891ae1df58c584d0a55775204308cff/src/sphinx_basic_ng/theme/basic-ng/page.html#L36-L40

**Comment by choldgraf** [comment]
that seems reasonable to me 👍 perhaps we should close this issue once this is documented?

**Comment by pradyunsg** [comment]
This now has a placeholder in the documentation, and likely doesn't need a dedicated issue to track filling that placeholder. :)
