### ISSUE TITLE
Should sphinx-basic-ng docs use sphinx-basic-ng theme?

### ISSUE THREAD

**Issue by JulienPalard** [pradyunsg/sphinx-basic-ng#20]
Looks like https://sphinx-basic-ng.readthedocs.io/en/latest/ is built using Furo, should it be built using sphinx-basic-ng? Would be an easy way to demo it, easier than screenshots to update.

**Comment by pradyunsg** [comment]
I will it in mind to properly clarify this, when fleshing out https://sphinx-basic-ng.readthedocs.io/en/latest/goals/ though!
