### ISSUE TITLE
How to use this in conjunction with CSS helper classes from frameworks like bootstrap?

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#27]
Many themes use a CSS framework with helper classes like Bootstrap to help lighten the burden of getting the right structure to a site.

However, some of these frameworks require specific HTML structures and classes, and I am wondering if it's possible to integrate this setup with the basic-ng theme's structure.

For example, for bootstrap the pydata theme uses patterns like

```html
<div class="row">
  <div class="col col-md-3 col-lg-5"></div>
  <div class="col"></div>
</div>
```

However, this theme has patterns like:

```html
{% block sidebar_primary %}
<aside class="sb-sidebar-primary">
  {% include "sections/sidebar-primary.html" %}
</aside>
{% endblock sidebar_primary %}
```

where users are encouraged to define their own HTML in `sections/sidebar-primary.html`.

In this case, it wouldn't be possible to use bootstrap to control the behavior of the sidebar, because the bootstrap classes would need to be added to the `aside` block, and moreover that block would need to be inside of a div with a `row` class. It would need to look like this:

```html
<div class="parent-container row">
	  <aside class="sb-sidebar-primary">
	    {% include "sections/sidebar-primary.html" %}
	  </aside>
	  <div class="sb-article-container col">
        {% headers articles etc %}
	  </div>
</div>
```

But I don't think that'd be possible without directly over-riding `layout.html` - is that correct?

**Comment by choldgraf** [comment]
One approach might be to recommend the use of [**grid mixins**](https://getbootstrap.com/docs/5.0/layout/grid/#mixins) (or generally, to use the mixin approach for SCSS frameworks). E.g. in bootstrap I think this would work:

```scss
.sb-container {
  @include make-container();
}
.sb-container__inner {
  @include make-row();
}
.sb-sidebar-primary {
  @include make-col-ready();

  @include media-breakpoint-up(sm) {
    @include make-col(3);
  }
  @include media-breakpoint-up(lg) {
    @include make-col(5);
  }

.sb-article-container {
  @include make-col-ready();
  @include make-col();
}

**Comment by pradyunsg** [comment]
I don't think it's feasible to use the scaffolding provided by sphinx-basic-ng with something like Bootstrap directly.

I imagine that you can fit the relevant containers _within_ sphinx-basic-ng's scaffolding but I don't see much value being derived from that? Out of the box, the scaffolding provides you with a responsive template to build upon; that has most of what you'd want from a three column layout.

If you don't want that, then you can override `page.html` to have whatever scaffolding you want. The only thing you need to worry about then are the few styles in skeleton.css that affect `html`, `body`, `article` and `[role='main']`. :)

**Comment by pradyunsg** [comment]
Closing this out, since I don't think there's more to discuss here. You know how to get hold of me, if you have more questions @choldgraf. :)
