### ISSUE TITLE
Support for on-premise instance for edit link

### ISSUE THREAD

**Issue by lalmeras** [pradyunsg/sphinx-basic-ng#35]
Edit link only supports SaaS instance (gitlab.com, github.com, bitbucket.org). github and gitlab (I don't know for bitbucket) allow on-premise instance, with custom urls.

Can we add a `source_provider` optional setting, with allowed values github|gitlab|bitbucket that override edit link building behavior and allow to use edit link with on-premise instance. If `source_provider` is missing, we can use startswith check to automatically handle gitlab.com/github.com/bitbucket.org cases.

I step into this issue as I use furo theme, and configuring edit link feature triggers `Could not understand "source_repository" provided` messages, and edit link is generated with an empty href.

**Comment by pradyunsg** [comment]
Merged that one, I'll cut a release and enable this in Furo sometime later in the week.
