### ISSUE TITLE
Removing the 3-column skeleton and supporting CSS

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/sphinx-basic-ng#38]
Looking at this project again, after a bit of a break, it seems like removing the "skeleton markup and styling for a 3-column website" from this theme and replacing it with a bare-bones layout that does what Sphinx's basic theme does (i.e. no-styling content placement) would be ideal.

Having tried to work with this in Lutra, it's actually quite annoying.... There's no easy way to tell your IDE that "hey, this project actually also uses classes and content from that other set of files in that virtual environment/local directory", and trying to figure out "hey, what thing controls the layout of that" is a non-trivial piece spread across two projects.

/cc @choldgraf @AakashGfude -- I believe both pydata and book themes were thinking of using this skeleton and experimenting with it. Any thoughts based on the work done around there?

**Comment by choldgraf** [comment]
Hmm - honestly, I don't think I'm a good person to ask about this. I haven't had time to dig into the basic-ng theme and I won't have time to do much development going forward, though am happy to support others in these efforts. I think the biggest benefit from this theme so far has been the _standardization_ that it has catalyzed for the pydata theme. We've renamed most things to use the structure and naming of this theme, but thus far have not made the actual switch. I know @aakashgfude was trying this out but hasn't picked it up in a little while.

If the skeleton / structural thing was gone, then what is the primary value proposition of this theme?

**Comment by pradyunsg** [comment]
The components -- which serve as shared implementations of common web design patterns.

**Comment by AakashGfude** [comment]
@pradyunsg @choldgraf I think the 3-column skeleton worked nicely for the themes of pydata and sphinx-book-theme, as both of them have the same structure. The classes and components were being inherited from what i remember working on this PR: https://github.com/pydata/pydata-sphinx-theme/pull/840 . And we did adjust some of the structural things in pydata-sphinx-theme to be in sync with sphinx-basic-ng skeleton.

**Comment by AakashGfude** [comment]
We can start working with the component inheritance of sphinx-basic-ng in pydata-sphinx-theme. Now that sbt has been updated to pydata 0.10 . As mentioned in this comment https://github.com/pydata/pydata-sphinx-theme/pull/840#issuecomment-1197545667. And see how we go?

**Comment by pradyunsg** [comment]
Sounds reasonable!

I'll close this out since... well, at the very least, we'll defer this until we have a better idea. :)

**Comment by choldgraf** [comment]
Ya agree - so for now if we depend on this base theme, it should just be for the reusable components and not for the skeleton.
