### ISSUE TITLE
Don't name sections of the page by function, just name them by location

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#5]
Sub-themes may or may not want to use each section of the page for the same thing. For example, the PyData Sphinx Theme uses the "topbar" as the "site nav" and the "left sidebar" as the "Section nav". I think this confusion would be smaller if the sections were named by their place in the page structure, rather than by the function we assume they'll have (e.g., `sidebar-left` and `sidebar-right`, rather than `site-nav`)

**Comment by pradyunsg** [comment]
I don't wanna do left/right because IMO we should support RTL here. That said, something like primary/secondary should work well!

**Comment by choldgraf** [comment]
Could you explain or point to a wrote up for why "right" and "left" language is problematic for RTL workflows ? I would have thought that RTL workflows is a *reason* to decouple the "location" from the "function" in naming things (since left does not always have to be the same function on the page, but it will always be "left")

**Comment by choldgraf** [comment]
Or in those cases do you imagine that the actual HTML positions of things would change location? If that's the case then i agree primary and secondary is better

**Comment by pradyunsg** [comment]
Yea, RTL sites should also flip the left-right sidebars and all that. Otherwise, the experience is a bit odd.

I guess a good way to imagine this would be PyData Sphinx theme but with the page toc on the left and site-section toc on the right.

**Comment by choldgraf** [comment]
yeah if that is possible, then I agree with you we should use non-location-specific terminology. "primary" and "secondary" sound good to me 👍
