### ISSUE TITLE
Agree on terminology for theme structures

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#9]
I think I've had some confusion because of the terminology used here. After thinking about it a bit, my understanding is that:

- **Components** are major areas of a page (e.g., sidebar, top bar, footer)
- **Elements** are snippets of HTML (w/ corresponding CSS rules) that you put inside of components

Is this right?

Could I suggest that we modify this slightly? To me, a `component` and an `element` are roughly equivalent conceptually. I think this is because of the association between "component" and [web components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) (which funnily enough, interchangeably uses `component` and `element` on that link).

# Proposal

Perhaps instead we could use

- **Sections** are major areas of a page (e.g., sidebar, top bar, footer)
- **Components** are snippets of HTML (w/ corresponding CSS rules) that you put inside of sections

(I don't care so much if we call the second thing `elements` or `components`, my main confusion is the use of `components` to refer to major areas of a page)

**Comment by pradyunsg** [comment]
Works for me! I'd say: let's use components for the latter. :)

**Comment by choldgraf** [comment]
OK cool - I modified my proposal in the top comment to use `components`. Will wait a bit to see if anybody else suggests we do something differently!
